---
- name: install mariadb server
  yum: name={{ item.name }} state=present
  with_items:
    - { name: 'epel-release' }
    - { name: 'python-devel' }
    - { name: 'python-pip' }
    - { name: 'mariadb' }
    - { name: 'mariadb-server' }
- name: start mariadb server
  service: name=mariadb state=started
- name: install pymysql
  pip:
    name: pymysql
    state: present
- mysql_user:
    name: ''
    host: localhost
    state: absent
- mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: set mariadb password
  mysql_user:
    name: root
    password: 'admin123'
